[nfs]
172.31.23.184 ansible_ssh_user='ec2-user'

[webservers]
172.31.24.18 ansible_ssh_user='ec2-user'
172.31.19.112 ansible_ssh_user='ec2-user'

[db]
172.31.31.252 ansible_ssh_user='ubuntu' 

[lb]
172.31.16.249 ansible_ssh_user='ubuntu'
