   pipeline {
    agent any

  stages {
    stage("initial cleanup") {
      steps{
        dir("${WORKSPACE}") {
          deletedir()
        }
      }
    }
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('packaging') {
      steps {
        script {
          sh 'echo "packaging App" '
        }
      }
    }

    stage('deploy') {
      steps {
        script {
          sh 'echo "Deploying to Dev" '
        }
      }
    }

    stage ("clean up") {
      steps{
        cleanws()
      }
    }
  }
   
}